#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Tue Jun 09 15:43:26 CST 2026
maven-metadata-aliyunmaven.xml.error=
maven-metadata-aliyunmaven.xml.lastUpdated=1780991006148
